image: Visual Studio 2017
skip_branch_with_pr: true
init:
# Set "build version number" to "short-commit-hash" or when tagged to "tag name"
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
    }
    else
    {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))"
    }
configuration:
- Debug
- Release
platform: x86
build:
  project: .\rslibs.sln
  verbosity: minimal
